/* AI3 private AI Lab UI. */
(()=>{
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opt={}){opt.headers={...(opt.headers||{})};const s=sessionStorage.getItem('ai3_admin_session'),k=sessionStorage.getItem('ai3_admin_key');if(s)opt.headers['X-AI3-Admin-Session']=s;else if(k)opt.headers['X-AI3-Admin-Key']=k;const r=await fetch(path,opt),t=await r.text();let d;try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.detail||d||`HTTP ${r.status}`);return d}
function table(h,r){return `<table class="table"><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r.join('')}</tbody></table>`}
function add(){if(document.getElementById('ai-lab'))return;const main=document.querySelector('main'),nav=document.querySelector('nav');if(!main||!nav)return;const b=document.createElement('button');b.className='nav';b.dataset.page='ai-lab';b.innerHTML='<i>🧠</i> AI Lab';nav.insertBefore(b,nav.children[1]||null);const page=document.createElement('section');page.id='ai-lab';page.className='page';page.innerHTML=`<div class="panel"><div class="eyebrow">PRIVATE AI / LEARNING / CODE</div><div class="row between"><div><h2>AI3 AI Lab</h2><p>Deine private KI-Werkstatt: Wissen beibringen, Projekte verwalten und lokal programmieren lassen.</p></div><span id="labStatus" class="secure">● lokal</span></div><div class="cards"><div class="card"><span>WISSEN</span><strong id="labKnowledge">—</strong><small>Einträge</small></div><div class="card"><span>PROJEKTE</span><strong id="labProjects">—</strong><small>eigene Projekte</small></div><div class="card"><span>DATEIEN</span><strong id="labFiles">—</strong><small>Projektdateien</small></div></div><div class="grid two"><div class="subpanel"><div class="eyebrow">TEACH</div><h3>Der KI etwas beibringen</h3><label>Titel<input id="teachTitle" placeholder="Mein Projektwissen"></label><label>Tags<input id="teachTags" placeholder="minecraft, lua, api"></label><label>Wissen / Anleitung<textarea id="teachContent" rows="9" placeholder="Dokumentation, Regeln, Code-Erklärungen oder eigene Notizen …"></textarea></label><button id="teachSave">Wissen speichern</button><div id="knowledgeList" class="table-wrap"></div></div><div class="subpanel"><div class="eyebrow">PRIVATE CHAT</div><h3>Mit deiner gelernten KI arbeiten</h3><label>Modell<select id="labModel"></select></label><label>Aufgabe<textarea id="labPrompt" rows="9" placeholder="Was soll die KI mit meinem Wissen machen?"></textarea></label><label><input id="labUseKnowledge" type="checkbox" checked> Eigenes Wissen verwenden</label><button id="labChat">▶ KI ausführen</button><pre id="labAnswer" class="codebox">Noch keine Anfrage.</pre></div></div><div class="subpanel"><div class="row between"><div><div class="eyebrow">CODING LAB</div><h3>Programmieren</h3><p>Die KI bekommt auf Wunsch die Dateien des ausgewählten Projekts als Kontext.</p></div><button id="newLabProject" class="secondary">＋ Projekt</button></div><div class="grid two"><div><label>Projekt<select id="labProject"></select></label><label>Sprache<input id="labLanguage" value="Python" placeholder="Python, Java, Lua, C++ …"></label><label>Modell<select id="codeModel"></select></label><label>Aufgabe<textarea id="codeTask" rows="8" placeholder="Baue / ändere / analysiere …"></textarea></label><label><input id="codeUseKnowledge" type="checkbox" checked> Eigenes Wissen verwenden</label><button id="runCode">⚡ Code-Aufgabe starten</button></div><div><label>Ergebnis</label><pre id="codeAnswer" class="codebox">Noch keine Code-Aufgabe.</pre></div></div></div></div>`;main.appendChild(page);
const show=()=>{document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='ai-lab'));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page==='ai-lab'));document.getElementById('pageTitle').textContent='AI Lab';document.getElementById('pageSubtitle').textContent='Deine private lernende KI und Coding-Werkstatt.';load()};b.onclick=show;
async function load(){try{const s=await api('/v1/admin/ai-lab/status');labKnowledge.textContent=s.knowledge_entries;labProjects.textContent=s.projects;labFiles.textContent=s.files;const m=await api('/v1/admin/local-models');const opts=(m.models||[]).map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('')||'<option value="">Kein Ollama-Modell</option>';labModel.innerHTML=opts;codeModel.innerHTML=opts;const p=await api('/v1/admin/ai-lab/projects');labProject.innerHTML=p.map(x=>`<option value="${x.id}">${esc(x.name)} — ${esc(x.language)}</option>`).join('')||'<option value="">Kein Projekt</option>';const k=await api('/v1/admin/ai-lab/knowledge');knowledgeList.innerHTML=table(['TITEL','TAGS','ZEICHEN','AKTION'],k.map(x=>`<tr><td><b>${esc(x.title)}</b></td><td>${esc(x.tags)}</td><td>${x.characters}</td><td><button class="danger" onclick="window.ai3DeleteKnowledge(${x.id})">Löschen</button></td></tr>`))}catch(e){labStatus.textContent='● '+e.message}}
teachSave.onclick=async()=>{try{if(!teachContent.value.trim())throw Error('Kein Wissen eingegeben');await api('/v1/admin/ai-lab/knowledge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:teachTitle.value.trim()||'Eigene Notiz',tags:teachTags.value.trim(),content:teachContent.value})});teachContent.value='';await load();alert('Wissen gespeichert.')}catch(e){alert(e.message)}};
window.ai3DeleteKnowledge=async id=>{if(!confirm('Wissen wirklich löschen?'))return;try{await api('/v1/admin/ai-lab/knowledge/'+id,{method:'DELETE'});load()}catch(e){alert(e.message)}};
labChat.onclick=async()=>{labAnswer.textContent='KI arbeitet …';try{const d=await api('/v1/admin/ai-lab/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:labModel.value,prompt:labPrompt.value,use_knowledge:labUseKnowledge.checked})});labAnswer.textContent=d.answer||JSON.stringify(d,null,2)}catch(e){labAnswer.textContent='Fehler: '+e.message}};
runCode.onclick=async()=>{codeAnswer.textContent='Coding-Agent arbeitet …';try{const d=await api('/v1/admin/ai-lab/code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:codeModel.value,project_id:labProject.value?Number(labProject.value):null,language:labLanguage.value,task:codeTask.value,use_knowledge:codeUseKnowledge.checked})});codeAnswer.textContent=d.answer||JSON.stringify(d,null,2)}catch(e){codeAnswer.textContent='Fehler: '+e.message}};
newLabProject.onclick=async()=>{const name=prompt('Projektname:');if(!name)return;const language=prompt('Sprache:','Python')||'text';try{await api('/v1/admin/ai-lab/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,language,description:''})});load()}catch(e){alert(e.message)}};
}
function boot(){add()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
