const state={key:sessionStorage.getItem('ai3_admin_key')||'',models:[]};const $=s=>document.querySelector(s);
async function api(path,opt={}){opt.headers={...(opt.headers||{}),'X-AI3-Admin-Key':state.key};const r=await fetch(path,opt);const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}if(!r.ok)throw new Error(data?.detail||data||`HTTP ${r.status}`);return data}
const names={dashboard:['Übersicht','Dein eigener KI- und Agent-Gateway.'],chat:['AI Studio','Direkt mit dem lokalen Modell sprechen.'],principals:['Agent Fleet','Identitäten und Modellrouting.'],tokens:['Token Hub','API-Zugriff zentral verwalten.'],models:['Model Hub','Lokale Modelle installieren.'],playground:['API Playground','OpenAI-kompatible Requests testen.'],usage:['Usage','Requests, Fehler und Latenz.'],connect:['Connect','OpenClaw, Open WebUI und SDKs verbinden.'],settings:['AI3 System','Betrieb und Administration.']};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function askKey(){const k=prompt('AI3 Admin-Schlüssel eingeben:');if(k){state.key=k;sessionStorage.setItem('ai3_admin_key',k);return true}return false}async function ensure(){if(!state.key&&!askKey())return false;try{await api('/v1/admin/status');return true}catch(e){state.key='';sessionStorage.removeItem('ai3_admin_key');alert('Admin-Schlüssel ungültig oder AI3 nicht erreichbar.');return !!askKey()}}
function show(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#pageTitle').textContent=names[page][0];$('#pageSubtitle').textContent=names[page][1];({dashboard:loadDashboard,principals:loadPrincipals,tokens:loadTokens,models:loadModels,usage:loadUsage,connect:loadConnect}[page]||(()=>{}))()};document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
function table(headers,rows){return `<table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`}
async function loadDashboard(){try{const h=await api('/v1/admin/status');$('#serverStatus').textContent='ONLINE';$('#serverTime').textContent=new Date().toLocaleString('de-DE');$('#llmStatus').textContent=(h.ollama||'LOCAL').toUpperCase();$('#backendName').textContent=h.backend||'ollama';$('#principalCount').textContent=h.principals??0;$('#requestCount').textContent=h.requests??0;$('#connectionDot').className='dot good';$('#connectionText').textContent='Online'}catch(e){$('#connectionDot').className='dot';$('#connectionText').textContent='Fehler'}}
async function loadPrincipals(){try{const p=await api('/v1/admin/principals');$('#principalsTable').innerHTML=table(['ID','NAME','TYP','ERSTELLT','STATUS'],p.map(x=>`<tr><td>${x.id}</td><td><b>${esc(x.name)}</b></td><td>${esc(x.kind)}</td><td>${new Date(x.created_at).toLocaleString('de-DE')}</td><td><span class="badge">● AKTIV</span></td></tr>`))}catch(e){$('#principalsTable').textContent=e.message}}
async function loadTokens(){try{const t=await api('/v1/admin/tokens');$('#tokensTable').innerHTML=table(['PREFIX','AGENT','NAME','SCOPES','ERSTELLT','STATUS','AKTION'],t.map(x=>`<tr><td><code>${esc(x.prefix)}</code></td><td>${esc(x.principal)}</td><td>${esc(x.name)}</td><td>${esc(x.scopes)}</td><td>${new Date(x.created_at).toLocaleString('de-DE')}</td><td><span class="badge ${x.active?'':'danger'}">${x.active?'● AKTIV':'WIDERRUFEN'}</span></td><td>${x.active?`<button class="danger" onclick="revoke('${esc(x.prefix)}')">Widerrufen</button>`:'—'}</td></tr>`))}catch(e){$('#tokensTable').textContent=e.message}}
async function revoke(prefix){if(!confirm(`Token ${prefix} wirklich widerrufen?`))return;try{await api('/v1/tokens/revoke?token_prefix='+encodeURIComponent(prefix),{method:'POST'});loadTokens()}catch(e){alert(e.message)}}
async function localModels(){try{return (await api('/v1/admin/local-models')).models||[]}catch{return []}}async function loadModels(){try{state.models=await localModels();$('#modelsTable').innerHTML=table(['MODELL','STATUS','GRÖSSE','AKTION'],state.models.map(x=>`<tr><td><code>${esc(x.name)}</code></td><td><span class="badge">● READY</span></td><td>${x.size?Math.round(x.size/1024/1024)+' MB':'—'}</td><td>Installiert</td></tr>`));fillModels()}catch(e){$('#modelsTable').textContent=e.message}}function fillModels(){['#chatModel','#playModel'].forEach(id=>{const s=$(id);if(s)s.innerHTML=state.models.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('')||'<option value="">Kein Modell</option>'})}
$('#refreshModels').onclick=loadModels;$('#newModel').onclick=()=>modal('Lokales Modell laden',`<p>Das Modell wird direkt auf deinem Ollama-Server geladen.</p><label>Ollama Modell<input name="name" required value="llama3.2:3b" placeholder="llama3.2:3b"></label><div class="form-actions"><button>Download starten</button></div>`,async f=>{const b=f.querySelector('button');b.disabled=true;b.textContent='Download läuft …';await api('/v1/admin/local-models/pull',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.name.value.trim()})});await loadModels();loadDashboard();alert('Modell bereit: '+f.name.value.trim())});
$('#newPrincipal').onclick=()=>modal('Neuer Agent',`<p>Erstelle eine eigene AI3-Identität.</p><label>Name<input name="name" required maxlength="100" placeholder="assistant-01"></label><label>Typ<select name="kind"><option>agent</option><option>user</option><option>service</option></select></label><div class="form-actions"><button>Agent anlegen</button></div>`,async f=>{await api('/v1/principals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.name.value,kind:f.kind.value})});loadPrincipals();loadDashboard()});
$('#newToken').onclick=async()=>{const p=await api('/v1/admin/principals');modal('Neuer Agent-Token',`<p>Der vollständige Token wird nur einmal angezeigt.</p><label>Agent<select name="principal">${p.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('')}</select></label><label>Name<input name="name" value="openclaw" required></label><label>Scopes</label><div class="checks"><label><input type="checkbox" name="ai" checked> ai:inference</label><label><input type="checkbox" name="agents" checked> agents:read</label></div><div class="form-actions"><button>Token erstellen</button></div>`,async f=>{const scopes=['ai:inference'];if(f.agents.checked)scopes.push('agents:read');const r=await api('/v1/tokens',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({principal:f.principal.value,name:f.name.value,scopes})});$('#tokenNotice').classList.remove('hidden');$('#tokenNotice').textContent='TOKEN – nur jetzt sichtbar:\n'+r.token;loadTokens()})};
function modal(title,html,submit){$('#modalTitle').textContent=title;$('#modalForm').innerHTML=html;$('#modal').classList.remove('hidden');$('#modalForm').onsubmit=async e=>{e.preventDefault();try{await submit(e.target);$('#modal').classList.add('hidden')}catch(x){alert(x.message)}}}$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};$('#logout').onclick=()=>{sessionStorage.clear();location.reload()};$('#changeKey').onclick=()=>{state.key='';sessionStorage.removeItem('ai3_admin_key');if(askKey())loadDashboard()};
let chatToken=sessionStorage.getItem('ai3_chat_token')||null;async function getAiToken(){if(chatToken)return chatToken;const key=prompt('Für AI Studio einen AI3-Token eingeben:');if(!key)throw new Error('Kein AI3-Token angegeben');chatToken=key;sessionStorage.setItem('ai3_chat_token',key);return key}function addMsg(type,text){const d=document.createElement('div');d.className='msg '+type;d.textContent=text;$('#messages').appendChild(d);$('#messages').scrollTop=$('#messages').scrollHeight;return d}
$('#chatForm').onsubmit=async e=>{e.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return;document.querySelector('.empty')?.remove();addMsg('user',text);input.value='';const bubble=addMsg('ai','Thinking …');try{const r=await fetch('/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+await getAiToken()},body:JSON.stringify({model:$('#chatModel').value,messages:[{role:'user',content:text}],stream:false})});const d=await r.json();if(!r.ok)throw new Error(d.detail||JSON.stringify(d));bubble.textContent=d.choices?.[0]?.message?.content||JSON.stringify(d)}catch(x){bubble.textContent='Fehler: '+x.message}};
$('#playRun').onclick=async()=>{let token=$('#playToken').value.trim();if(!token)token=await getAiToken();$('#playOutput').textContent='Sende Anfrage …';try{const r=await fetch('/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({model:$('#playModel').value,messages:[{role:'user',content:$('#playPrompt').value}],stream:false})});const text=await r.text();let d;try{d=JSON.parse(text)}catch{d=text}$('#playOutput').textContent=JSON.stringify(d,null,2)}catch(e){$('#playOutput').textContent=e.message}};
async function loadUsage(){try{const d=await api('/v1/admin/usage');$('#usageTotal').textContent=d.total_requests;$('#usageErrors').textContent=d.errors;$('#usageRate').textContent=(d.error_rate*100).toFixed(1)+'% Fehler';$('#usageLatency').textContent=Math.round(d.avg_latency_ms);$('#usageTable').innerHTML=table(['ENDPOINT','REQUESTS','Ø LATENZ'],d.endpoints.map(x=>`<tr><td><code>${esc(x.endpoint)}</code></td><td>${x.requests}</td><td>${Math.round(x.avg_ms)} ms</td></tr>`))}catch(e){$('#usageTable').textContent=e.message}}$('#refreshUsage').onclick=loadUsage;
async function loadConnect(){const url=location.origin+'/v1',model=state.models[0]?.name||'YOUR_MODEL';$('#apiUrl').textContent=url;$('#webUrl').textContent=location.origin;$('#apiUrlSettings').textContent=url;$('#connectModel').textContent=model;$('#backendSettings').textContent='Ollama / '+model;$('#versionSettings').textContent='AI3 3.0.0';$('#sdkExample').textContent=`from openai import OpenAI\n\nclient = OpenAI(base_url="${url}", api_key="YOUR_AI3_TOKEN")\nresponse = client.chat.completions.create(model="${model}", messages=[{"role":"user","content":"Hallo AI3"}])\nprint(response.choices[0].message.content)`;$('#openclawExample').textContent=`models: {\n  providers: {\n    ai3: {\n      baseUrl: "${url}",\n      apiKey: "YOUR_AI3_TOKEN",\n      api: "openai-completions",\n      models: [{ id: "${model}", name: "AI3 Local" }]\n    }\n  }\n}`}
async function boot(){if(await ensure()){await loadModels();loadDashboard();loadConnect()}}boot();
