const state={key:sessionStorage.getItem('ai3_admin_key')||'',models:[]};
const $=s=>document.querySelector(s);
async function api(path,opt={}){opt.headers={...(opt.headers||{}),'X-AI3-Admin-Key':state.key};const r=await fetch(path,opt);const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}if(!r.ok)throw new Error(data?.detail||data||`HTTP ${r.status}`);return data}
function askKey(){let k=prompt('AI3 Admin-Schlüssel eingeben:');if(k){state.key=k;sessionStorage.setItem('ai3_admin_key',k);return true}return false}
async function ensure(){if(!state.key&&!askKey())return false;try{await api('/health');return true}catch(e){if(e.message.includes('admin')){state.key='';sessionStorage.removeItem('ai3_admin_key');alert('Admin-Schlüssel ungültig.');return askKey()&&ensure()}return true}}
function show(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const names={dashboard:['Dashboard','AI3 Token Server & lokales KI-Gateway'],chat:['AI Chat','Direkt mit dem lokalen Modell sprechen'],principals:['Benutzer & Agents','Identitäten für AI3-Clients'],tokens:['Token','API-Zugriff verwalten'],models:['Modelle','Verfügbare lokale KI-Modelle'],settings:['Verbindung','Server- und Admin-Einstellungen']};$('#pageTitle').textContent=names[page][0];$('#pageSubtitle').textContent=names[page][1];if(page==='dashboard')loadDashboard();if(page==='principals')loadPrincipals();if(page==='tokens')loadTokens();if(page==='models')loadModels()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
async function loadDashboard(){try{const h=await fetch('/health').then(r=>r.json());$('#serverStatus').textContent='Online';$('#serverTime').textContent=new Date(h.time).toLocaleString('de-DE');$('#llmStatus').textContent=h.llm_configured?'Konfiguriert':'Nicht konfiguriert';$('#connectionDot').className='dot good';$('#connectionText').textContent='Verbunden';const p=await api('/v1/admin/principals');$('#principalCount').textContent=p.length;const m=await api('/v1/admin/models');$('#modelCount').textContent=m.data?.length??0}catch(e){$('#connectionDot').className='dot';$('#connectionText').textContent='Fehler';}}
function table(headers,rows){return `<table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`}
async function loadPrincipals(){try{const p=await api('/v1/admin/principals');$('#principalsTable').innerHTML=table(['ID','Name','Typ','Erstellt','Status'],p.map(x=>`<tr><td>${x.id}</td><td>${esc(x.name)}</td><td>${esc(x.kind)}</td><td>${new Date(x.created_at).toLocaleString('de-DE')}</td><td><span class="badge">Aktiv</span></td></tr>`))}catch(e){$('#principalsTable').textContent=e.message}}
async function loadTokens(){try{const t=await api('/v1/admin/tokens');$('#tokensTable').innerHTML=table(['Prefix','Principal','Name','Scopes','Erstellt','Status','Aktion'],t.map(x=>`<tr><td><code>${x.prefix}</code></td><td>${esc(x.principal)}</td><td>${esc(x.name)}</td><td>${esc(x.scopes)}</td><td>${new Date(x.created_at).toLocaleString('de-DE')}</td><td><span class="badge ${x.active?'':'danger'}">${x.active?'Aktiv':'Widerrufen'}</span></td><td>${x.active?`<button class="danger" onclick="revoke('${x.prefix}')">Widerrufen</button>`:'—'}</td></tr>`))}catch(e){$('#tokensTable').textContent=e.message}}
async function revoke(prefix){if(!confirm(`Token ${prefix} wirklich widerrufen?`))return;try{await api('/v1/tokens/revoke?token_prefix='+encodeURIComponent(prefix),{method:'POST'});loadTokens()}catch(e){alert(e.message)}}
async function loadModels(){try{const d=await api('/v1/admin/models');state.models=d.data||[];$('#modelsTable').innerHTML=table(['ID','Objekt','Besitzer'],state.models.map(x=>`<tr><td><code>${esc(x.id)}</code></td><td>${esc(x.object||'model')}</td><td>${esc(x.owned_by||'local')}</td></tr>`));fillModelSelect()}catch(e){$('#modelsTable').textContent=e.message}}
function fillModelSelect(){const s=$('#chatModel');s.innerHTML=state.models.map(x=>`<option value="${esc(x.id)}">${esc(x.id)}</option>`).join('')||'<option value="">Kein Modell</option>'}
$('#refreshModels').onclick=loadModels;
$('#newPrincipal').onclick=()=>modal('Neuer Principal',`<label>Name<input name="name" required maxlength="100" placeholder="assistant-01"></label><label>Typ<select name="kind"><option>agent</option><option>user</option><option>service</option></select></label><div class="form-actions"><button>Erstellen</button></div>`,async f=>{await api('/v1/principals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.name.value,kind:f.kind.value})});loadPrincipals()});
$('#newToken').onclick=async()=>{let p=await api('/v1/admin/principals');modal('Neuer API-Token',`<label>Principal<select name="principal">${p.map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('')}</select></label><label>Name<input name="name" value="openclaw" required></label><label>Scopes</label><div class="checks"><label><input type="checkbox" name="ai" checked> ai:inference</label><label><input type="checkbox" name="agents" checked> agents:read</label></div><div class="form-actions"><button>Token erstellen</button></div>`,async f=>{let scopes=['ai:inference'];if(f.agents.checked)scopes.push('agents:read');let r=await api('/v1/tokens',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({principal:f.principal.value,name:f.name.value,scopes})});$('#tokenNotice').classList.remove('hidden');$('#tokenNotice').textContent='TOKEN – nur jetzt sichtbar:\n'+r.token;loadTokens()})};
function modal(title,html,submit){$('#modalTitle').textContent=title;$('#modalForm').innerHTML=html;$('#modal').classList.remove('hidden');$('#modalForm').onsubmit=async e=>{e.preventDefault();try{await submit(e.target);$('#modal').classList.add('hidden')}catch(x){alert(x.message)}}}
$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};$('#logout').onclick=()=>{state.key='';sessionStorage.removeItem('ai3_admin_key');location.reload()};$('#changeKey').onclick=()=>{state.key='';sessionStorage.removeItem('ai3_admin_key');if(askKey())loadDashboard()};
$('#chatForm').onsubmit=async e=>{e.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return;const empty=document.querySelector('.empty');if(empty)empty.remove();addMsg('user',text);input.value='';const bubble=addMsg('ai','…');try{const model=$('#chatModel').value;const r=await api('/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+await getAiToken()},body:JSON.stringify({model,messages:[{role:'user',content:text}],stream:false})});bubble.textContent=r.choices?.[0]?.message?.content||JSON.stringify(r)}catch(x){bubble.textContent='Fehler: '+x.message}}
let chatToken=null;async function getAiToken(){if(chatToken)return chatToken;const key=prompt('Für den Chat wird ein AI3-Token benötigt. Token eingeben:');if(!key)throw new Error('Kein AI3-Token angegeben');chatToken=key;return key}
function addMsg(type,text){const d=document.createElement('div');d.className='msg '+type;d.textContent=text;$('#messages').appendChild(d);$('#messages').scrollTop=$('#messages').scrollHeight;return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#apiUrl').textContent=location.origin+'/v1';$('#webUrl').textContent=location.origin+'/';
async function boot(){if(await ensure()){loadDashboard();loadModels()}}boot();
