/* AI3 / xDarkixx branding, legal information, live runtime limits and network status. */
(()=>{
const $=s=>document.querySelector(s);
async function api(path,opt={}){opt.headers={...(opt.headers||{})};const session=sessionStorage.getItem('ai3_admin_session'),key=sessionStorage.getItem('ai3_admin_key');if(session)opt.headers['X-AI3-Admin-Session']=session;else if(key)opt.headers['X-AI3-Admin-Key']=key;const r=await fetch(path,opt),text=await r.text();let d;try{d=JSON.parse(text)}catch{d=text}if(!r.ok)throw new Error(d?.detail||d||`HTTP ${r.status}`);return d}
function showLegal(){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='legal'));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page==='legal'));$('#pageTitle').textContent='Rechtliche Hinweise';$('#pageSubtitle').textContent='Copyright, Datenschutz und Betreiberhinweise.'}
function addLegal(){const main=document.querySelector('main');if(!main)return;const page=document.createElement('section');page.id='legal';page.className='page';page.innerHTML=`<div class="panel legal-panel"><div class="eyebrow">AI3 / X DARKIXX</div><h2>Rechtliche Hinweise</h2><p>AI3 ist selbst gehostete Software. Diese Hinweise sind allgemeine Produktinformationen und keine Rechtsberatung.</p><div class="legal-grid"><article><h3>Urheberrecht</h3><p>© 2026 xDarkixx — AI3. Alle Rechte an der AI3-eigenen Oberfläche, Kennzeichnung und den von xDarkixx erstellten Bestandteilen bleiben vorbehalten, soweit nicht ausdrücklich eine andere Lizenz angegeben ist.</p></article><article><h3>Haftung</h3><p>Der Betreiber ist selbst für Installation, Konfiguration, Zugangsschutz, Modellinhalte, Backups, Datenschutz und die Einhaltung der am Einsatzort geltenden Gesetze verantwortlich.</p></article><article><h3>Datenschutz</h3><p>Eine öffentliche Instanz sollte eine eigene Datenschutzerklärung bereitstellen und transparent erklären, welche Logs, IP-Adressen, Nutzungsdaten und Zugangsdaten verarbeitet werden.</p></article><article><h3>Impressum</h3><p>Bei einem öffentlich angebotenen Dienst müssen die Betreiberangaben passend zur Rechtsform und zum Land ergänzt werden. AI3 erfindet bewusst keine persönlichen Betreiberangaben.</p></article></div><div class="notice">AI3 benötigt für lokale Inferenz keinen kostenpflichtigen KI-API-Anbieter. Hardware-, Strom-, Internet-, Domain- und gegebenenfalls Modelllizenzkosten sind davon getrennt.</div></div>`;main.appendChild(page);const nav=document.createElement('button');nav.className='nav';nav.dataset.page='legal';nav.innerHTML='<i>§</i> Rechtliches';document.querySelector('nav')?.appendChild(nav);nav.onclick=showLegal;const footer=document.createElement('footer');footer.className='ai3-footer';footer.innerHTML=`<span>© 2026 xDarkixx — AI3</span><button class="footer-link" id="legalOpen">Rechtliche Hinweise</button>`;main.appendChild(footer);$('#legalOpen').onclick=showLegal}
function addLimits(){const panel=document.querySelector('#settings .panel');if(!panel)return;const section=document.createElement('div');section.className='limit-section';section.innerHTML=`<hr><div class="eyebrow">RUNTIME POLICY</div><h3>Limits & Kontingente</h3><p><b>0 = unbegrenzt.</b> Requests/Minute und Tageskontingent werden sofort angewendet.</p><div class="limit-grid"><label>Requests / Minute<input id="limitRpm" type="number" min="0" value="0"></label><label>Requests / 24 Stunden<input id="limitDaily" type="number" min="0" value="0"></label></div><div class="actions"><button id="saveLimits">Limits speichern</button><button id="unlimitedLimits" class="secondary">♾ Alles unbegrenzt</button></div><p id="limitStatus" class="muted"></p>`;panel.appendChild(section);const set=d=>{const x=d.limits||{};$('#limitRpm').value=x.rate_limit_rpm??0;$('#limitDaily').value=x.daily_request_limit??0};(async()=>{try{set(await api('/v1/admin/limits'))}catch(e){$('#limitStatus').textContent=e.message}})();$('#saveLimits').onclick=async()=>{try{const body={rate_limit_rpm:+$('#limitRpm').value,daily_request_limit:+$('#limitDaily').value,max_input_tokens:0,max_output_tokens:0,max_concurrent_requests:0};set(await api('/v1/admin/limits',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));$('#limitStatus').textContent='Gespeichert.'}catch(e){$('#limitStatus').textContent=e.message}};$('#unlimitedLimits').onclick=async()=>{try{set(await api('/v1/admin/limits/unlimited',{method:'POST'}));$('#limitStatus').textContent='Alle Limits: unbegrenzt.'}catch(e){$('#limitStatus').textContent=e.message}}}
function addNetworkStatus(){const panel=document.querySelector('#settings .panel');if(!panel)return;const section=document.createElement('div');section.className='network-section';section.innerHTML=`<hr><div class="eyebrow">NETWORK / SELF-HEALING</div><div class="row between"><div><h3>System & Netzwerk</h3><p>AI3 erkennt die aktuelle LAN-Adresse automatisch und aktualisiert den Gateway bei DHCP-Änderungen.</p></div><span id="networkLive" class="secure">● wird geprüft</span></div><div class="info-grid"><div><span>PC-Name</span><strong id="networkHostname">—</strong></div><div><span>LAN-IP</span><strong id="networkIp">—</strong></div><div><span>Router / Gateway</span><strong id="networkGateway">—</strong></div><div><span>Netzwerkadapter</span><strong id="networkInterface">—</strong></div><div><span>Letzte Aktualisierung</span><strong id="networkUpdated">—</strong></div><div><span>Router-Ziel</span><strong id="networkPorts">TCP 80 / 443</strong></div></div><div class="actions"><button id="openRouter">↗ Router öffnen</button><button id="networkGuide" class="secondary">ⓘ Anleitung</button><button id="refreshNetwork" class="secondary">↻ Jetzt prüfen</button></div><p class="muted">Wichtig: AI3 ändert die Router-Portweiterleitung nicht automatisch. Du richtest den Router einmal auf diesen PC als Ziel ein; danach folgt AI3 der LAN-IP selbstständig.</p></div>`;panel.appendChild(section);
const render=d=>{if(!d)return;$('#networkHostname').textContent=d.hostname||'—';$('#networkIp').textContent=d.ip||'—';$('#networkGateway').textContent=d.gateway||'—';$('#networkInterface').textContent=d.interface||'—';$('#networkUpdated').textContent=d.updated_at?new Date(d.updated_at).toLocaleString('de-DE'):'—';$('#networkPorts').textContent=(d.router_target?.tcp||[80,443]).map(p=>`TCP ${p}`).join(' / ');$('#networkLive').textContent=d.automatic_lan_refresh?'● automatische LAN-Erkennung aktiv':'● Status unbekannt';};
async function load(){try{const r=await fetch(`/__ai3/network-info.json?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);render(await r.json())}catch(e){$('#networkLive').textContent='● Netzwerkstatus nicht erreichbar';$('#networkUpdated').textContent=e.message}}
$('#openRouter').onclick=async()=>{try{const r=await fetch(`/__ai3/network-info.json?ts=${Date.now()}`,{cache:'no-store'});const d=await r.json();if(/^\d{1,3}(\.\d{1,3}){3}$/.test(d.gateway||''))window.open(`http://${d.gateway}/`,'_blank','noopener');else alert('Router-Adresse ist noch nicht verfügbar.')}catch(e){alert('Router-Adresse konnte nicht ermittelt werden.')}};
$('#networkGuide').onclick=()=>alert('Router-Anleitung\n\n1. Router öffnen.\n2. Diesen PC anhand des angezeigten PC-Namens bzw. der LAN-IP auswählen.\n3. TCP 80 und TCP 443 auf diesen PC weiterleiten.\n4. AI3 überwacht danach die LAN-IP automatisch.\n\nEine DHCP-Reservierung für diesen PC wird zusätzlich empfohlen.');
$('#refreshNetwork').onclick=load;load();setInterval(load,30000)}
function boot(){addLegal();addLimits();addNetworkStatus()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
