/* AI3 / xDarkixx branding, legal information and live runtime-limit controls. */
(()=>{
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function addLegal(){
 const main=document.querySelector('main'); if(!main)return;
 const page=document.createElement('section'); page.id='legal'; page.className='page'; page.innerHTML=`<div class="panel legal-panel"><div class="eyebrow">AI3 / X DARKIXX</div><h2>Rechtliche Hinweise</h2><p>AI3 ist selbst gehostete Software. Die folgenden Hinweise sind allgemeine Produktinformationen und keine Rechtsberatung.</p><div class="legal-grid"><article><h3>Urheberrecht</h3><p>© 2026 xDarkixx — AI3. Alle Rechte an der AI3-eigenen Oberfläche, Kennzeichnung und den von xDarkixx erstellten Bestandteilen bleiben vorbehalten, soweit nicht ausdrücklich eine andere Lizenz angegeben ist.</p></article><article><h3>Haftung</h3><p>Der Betreiber ist selbst für Installation, Konfiguration, Zugangsschutz, Modellinhalte, Backups, Datenschutz und die Einhaltung der am Einsatzort geltenden Gesetze verantwortlich.</p></article><article><h3>Datenschutz</h3><p>Eine öffentliche Instanz sollte eine eigene Datenschutzerklärung bereitstellen und transparent erklären, welche Logs, IP-Adressen, Nutzungsdaten und Zugangsdaten verarbeitet werden.</p></article><article><h3>Impressum</h3><p>Bei einem öffentlich angebotenen Dienst müssen die Betreiberangaben passend zur Rechtsform und zum Land ergänzt werden. AI3 liefert bewusst keine erfundenen persönlichen Daten.</p></article></div><div class="notice">AI3 selbst verpflichtet dich nicht zu einem kostenpflichtigen KI-Provider. Lokale Modelle können ohne externe KI-API-Gebühren betrieben werden. Infrastruktur-, Strom-, Internet-, Domain- und gegebenenfalls Modelllizenzkosten sind davon getrennt.</div></div>`;
 main.appendChild(page);
 const nav=document.createElement('button'); nav.className='nav'; nav.dataset.page='legal'; nav.innerHTML='<i>§</i> Rechtliches'; document.querySelector('nav')?.appendChild(nav); nav.onclick=()=>window.ai3Show?.('legal');
 const footer=document.createElement('footer'); footer.className='ai3-footer'; footer.innerHTML=`<span>© 2026 xDarkixx — AI3</span><button class="footer-link" id="legalOpen">Rechtliche Hinweise</button>`; main.appendChild(footer); $('#legalOpen').onclick=()=>window.ai3Show?.('legal');
}
function addLimits(){
 const panel=document.querySelector('#settings .panel'); if(!panel)return;
 const section=document.createElement('div'); section.className='limit-section'; section.innerHTML=`<hr><div class="eyebrow">RUNTIME POLICY</div><h3>Limits & Kontingente</h3><p><b>0 = unbegrenzt.</b> Änderungen werden sofort für neue Requests übernommen.</p><div class="limit-grid"><label>Requests / Minute<input id="limitRpm" type="number" min="0" value="0"></label><label>Requests / 24 Stunden<input id="limitDaily" type="number" min="0" value="0"></label><label>Max. Input-Tokens<input id="limitInput" type="number" min="0" value="0"></label><label>Max. Output-Tokens<input id="limitOutput" type="number" min="0" value="0"></label><label>Max. parallele Requests<input id="limitConcurrent" type="number" min="0" value="0"></label></div><div class="actions"><button id="saveLimits">Limits speichern</button><button id="unlimitedLimits" class="secondary">♾ Alles unbegrenzt</button></div><p id="limitStatus" class="muted"></p>`; panel.appendChild(section);
 const set=(d)=>{const x=d.limits||{}; $('#limitRpm').value=x.rate_limit_rpm??0;$('#limitDaily').value=x.daily_request_limit??0;$('#limitInput').value=x.max_input_tokens??0;$('#limitOutput').value=x.max_output_tokens??0;$('#limitConcurrent').value=x.max_concurrent_requests??0};
 async function load(){try{set(await window.ai3Api('/v1/admin/limits'));}catch(e){$('#limitStatus').textContent='Limits: '+e.message}}
 $('#saveLimits').onclick=async()=>{try{const body={rate_limit_rpm:+$('#limitRpm').value,daily_request_limit:+$('#limitDaily').value,max_input_tokens:+$('#limitInput').value,max_output_tokens:+$('#limitOutput').value,max_concurrent_requests:+$('#limitConcurrent').value};set(await window.ai3Api('/v1/admin/limits',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));$('#limitStatus').textContent='Gespeichert.'}catch(e){$('#limitStatus').textContent=e.message}};
 $('#unlimitedLimits').onclick=async()=>{try{set(await window.ai3Api('/v1/admin/limits/unlimited',{method:'POST'}));$('#limitStatus').textContent='Alle Limits: unbegrenzt.'}catch(e){$('#limitStatus').textContent=e.message}};
 load();
}
window.ai3Show=page=>{document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const title=page==='legal'?'Rechtliche Hinweise':page==='settings'?'AI3 System':page;const t=document.querySelector('#pageTitle');if(t)t.textContent=title;const s=document.querySelector('#pageSubtitle');if(s)s.textContent=page==='legal'?'Copyright, Datenschutz und Betreiberhinweise.':'';};
window.ai3Api=window.ai3Api||null;
function boot(){addLegal();addLimits();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
